### ISSUE TITLE
Consul back-end results in error: spec.backend is not specified

### ISSUE THREAD

**Issue by slybit** [kubevault/issues#61]
Hi,

I get an error when trying to use the consul backend.

My spec:

```
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: op
spec:
  nodes: 1
  version: "1.0.1"
  backend:
    consul:
      address: "http://opconsul.op.svc:8500"
      path: "vault"
```

Error when creating the VaulServer:
```
> kubectl create -f vault-server-operator.yaml -n op
Error from server (Forbidden): error when creating "vault-server-operator.yaml": admission webhook "vaultservers.validators.kubevault.com" denied the request: spec.backend is not specified
```
If I use the `inmem: {}' backend is works...
I assume I might be omitting some required field of the consul backend?
