### ISSUE TITLE
How to inject ENV variables

### ISSUE THREAD

**Issue by slybit** [kubevault/issues#62]
Hi,

Is it possible to inject ENVIRONMENT variables in the Vault container from the VaultService definition yaml file? I would like to use it to inject this:
```
- name: VAULT_SEAL_TYPE
      value: "awskms"   
    - name: AWS_REGION
      valueFrom:
        secretKeyRef:
          name: vault-unseal-secrets
          key: AWS_REGION       
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: vault-unseal-secrets
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: vault-unseal-secrets
          key: AWS_SECRET_ACCESS_KEY
    - name: VAULT_AWSKMS_SEAL_KEY_ID
      valueFrom:
        secretKeyRef:
          name: vault-unseal-secrets
          key: VAULT_AWSKMS_SEAL_KEY_ID
```
for automatic unsealing of vault using its built-in mechanism
