### ISSUE TITLE
I am not able to add annotation for kube2iam role in vaultserver yaml file

### ISSUE THREAD

**Issue by pravinkumarb84** [kubevault/issues#68]
I am not able to add annotation for kube2iam role in vaultserver yaml file

I am using this spec file for vaultServer deployment:

```
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: my-vault-demo
  namespace: dev
spec:
   metadata:
        annotations:  
            iam.amazonaws.com/role: k8s-vault
   nodes: 1
   version: "0.11.5"
   backend:
       s3:
          bucket: "my demo s3"
          region: "eu-west-2"
   unsealer:
       secretShares: 4
       secretThreshold: 2
       mode:
            awsKmsSsm:
                 region: "eu-west-2"
                 kmsKeyID: "my kms key"

```
