### ISSUE TITLE
Not able to update/override busybox initContainer image location for vault server

### ISSUE THREAD

**Issue by pravinkumarb84** [kubevault/issues#69]
Hi Folks,
I am running vault-operator-0.2.0 and vault server in my dev namespace. And I have my private registry to pull the images.

with the current config for vault server, I am not able to update/override the image for busybox initcontainer.It always goes to the docker hub for pulling the image.

I tried this in the vaultserver.yaml file

```
spec:
  serviceTemplate:
    metadata:
      annotations:
        iam.amazonaws.com/role: k8s-vault
  podTemplate:
    spec:
      initContainers:
      - name: vault-config
        image: `my image repo path`
      imagePullSecrets:
      - name: ecr-docker-credentials 
```
```
 
Warning  Failed                 53s                kubelet, *******.compute.internal  Failed to pull image "busybox": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: read tcp 10.54.163.182:47794->54.175.43.85:443: read: connection reset by peer
```

```
```
